---
title: "HW4"
output: html_document
---
##Load relevant packages
```{r}
library(GEOquery)
library(limma)
library(pheatmap)
library(GSEABase)
```

##Get data with GEOquery and clean
```{r}
gd <- getGEO("GSE45735", destdir="./")
pd <- pData(gd[[1]])
getGEOSuppFiles("GSE45735", makeDirectory=FALSE, baseDir = ".")

# Note the regular expression to grep file names
files <- list.files(path = ".", pattern = "GSE45735_T.*.gz", full.names = TRUE)

# Read in gzip-compressed, tab-delimited files
file_list <- lapply(files, read.table, sep='\t', header=TRUE)
# Subset to only those rows where Gene contains only non-space characters
# This addresses problems with T14 file containing 28 invalid rows at end of file
file_list <- lapply(file_list, function(file_list)subset(file_list, grepl('^[^[:space:]]+$', Gene)))

# Remove duplicated rows
file_list_unique <- lapply(file_list, function(x){x<-x[!duplicated(x$Gene),]; 
                                                  x <- x[order(x$Gene),]; 
                                                  rownames(x) <- x$Gene;
                                                  x[,-1]})
# Take the intersection of all genes
gene_list <- Reduce(intersect, lapply(file_list_unique, rownames))
file_list_unique <- lapply(file_list_unique, "[", gene_list,)
matrix <- as.matrix(do.call(cbind, file_list_unique))

# Clean up the pData
pd_small <- pd[!grepl("T13_Day8",pd$title),]
pd_small$Day <- sapply(strsplit(gsub(" \\[PBMC\\]", "", pd_small$title),"_"),"[",2)
pd_small$subject <- sapply(strsplit(gsub(" \\[PBMC\\]", "", pd_small$title),"_"),"[",1)
colnames(matrix) <- rownames(pd_small)
```

##Voom and limma to find differentially expressed genes at FDR=0.01
```{r}
# Note that I add one to the count
new_set <- ExpressionSet(assayData = matrix+1)
pData(new_set) <- pd_small

#voom and limma
design <- model.matrix(~subject+Day, new_set)
new_set_voom <- voom(new_set,design = design)
lm <- lmFit(new_set_voom, design)
eb <- eBayes(lm)

genes <- vector("list", length = 10)
for(i in 1:10) {
  coef <- paste0("DayDay", i)
  genes[[i]] <- topTable(eb, coef = coef, number=Inf)
}

## heatmap with FDR=0.01
PValue <- sapply(genes, function(x){x$adj.P.Val})
LogFC <- sapply(genes, function(x){x$logFC})
rownames(LogFC) <- rownames(genes[[1]])
PValue_min <- rowMin(PValue)
LogFC_01 <- LogFC[PValue_min<0.01, ]
anno <- data.frame(Time=paste0("Day", 1:10))
rownames(anno) <- colnames(LogFC_01) <- paste0("Day", 1:10)
pheatmap(LogFC_01, cluster_cols=FALSE)
```

##GSEA with camera and MSigDB Reactome pathway gene signatures
from lecture notes
```{r}
c2_set <- getGmt("GSEA-sets/c2.all.v4.0.symbols.gmt")
gene_ids <- geneIds(c2_set)
if (exists("ids2indices")) { 
    sets_indices <- ids2indices(gene_ids, rownames(new_set))
}
if (exists("symbols2indices")) {
    sets_indices <- symbols2indices(gene_ids, rownames(new_set))    
}
## Finding enriched gene sets over time
res <- vector("list",length = 10)
for(i in 1:10)
  {
  contrast <- paste0("DayDay",i)
  cont_matrix <- makeContrasts(contrast, levels=design)
  res[[i]] <- camera(new_set_voom, sets_indices, design=design, contrast=cont_matrix, sort=FALSE)
}

## Visualizing the results with heatmap
PValue <- sapply(res, function(x){ifelse(x$Direction=="Up", -10*log10(x$PValue), 10*log10(x$PValue))})
rownames(PValue) <- rownames(res[[1]])
PValue_max <- rowMax(abs(PValue))
PValue_small <- PValue[PValue_max>30, ]
anno <- data.frame(Time=paste0("Day",1:10))
rownames(anno) <- colnames(PValue_small)  <- paste0("Day",1:10)
pheatmap(PValue_small, cluster_cols=FALSE)
```